// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpi_rM3ggZOOUUYJ4ExXn2in-OS_Pnguw',
    appId: '1:906981306800:web:ae3f61d57d3ee57d1d2675',
    messagingSenderId: '906981306800',
    projectId: 'test-31e58',
    authDomain: 'test-31e58.firebaseapp.com',
    storageBucket: 'test-31e58.appspot.com',
    measurementId: 'G-Z5D7L319M9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqC4dBsxGKCfnqgUwhmpbbONHy-OIUu58',
    appId: '1:906981306800:android:4895d2e0a73211ad1d2675',
    messagingSenderId: '906981306800',
    projectId: 'test-31e58',
    storageBucket: 'test-31e58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANQnXI_VHOj1BWtm_u70w6bzTgEt6eDrw',
    appId: '1:906981306800:ios:65a3caa33914e4c31d2675',
    messagingSenderId: '906981306800',
    projectId: 'test-31e58',
    storageBucket: 'test-31e58.appspot.com',
    iosClientId: '906981306800-9hkpc80gpj71r6bgoeu1kultp89d4mub.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANQnXI_VHOj1BWtm_u70w6bzTgEt6eDrw',
    appId: '1:906981306800:ios:0c65094ef3aed59b1d2675',
    messagingSenderId: '906981306800',
    projectId: 'test-31e58',
    storageBucket: 'test-31e58.appspot.com',
    iosClientId: '906981306800-3lor1fpa4k4stgaq6q5h87tn541ja3kl.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
